### ISSUE TITLE
Stack creation fails with "API: s3:SetBucketEncryption Access Denied" error

### ISSUE THREAD

**Issue by jayrao** [aws-solutions/aws-content-analysis#53]
**Describe the bug**
While launching this template, the nested stack "MieStack" fails with following error.

"API: s3:SetBucketEncryption Access Denied" for the resource Logical ID "DataplaneLogsBucket" 

**To Reproduce**
Just launch the stack in either regions and it throws the error. As stack gets rolled back and resources deleted, I cannot proceed further.

**Expected behavior**
Stack should launch without any error.

**Please complete the following information about the solution:**
(SO0163) - aws-media-insights-engine v3.0.2 for the nested stack
(SO0042) - aws-content-analysis v2.0.0 for the root stack

- Region: [us-east-1 and us-west-2]
- [No] Was the solution modified from the version published on this repository?
- [n/a] If the answer to the previous question was yes, are the changes available on GitHub?
- [n/a] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
- [No] Were there any errors in the CloudWatch Logs?

**Comment by ianwow** [comment]
investigating...

**Comment by jayrao** [comment]
Thanks. It was an Organization SCP blocking permission to enable SSE on buckets.
