### ISSUE TITLE
Conflict with

### ISSUE THREAD

**Issue by gmarchand** [aws-solutions/aws-content-analysis#7]
This resource `WorkflowExecutionLambdaDeadLetterQueue` has a fixed name and it's in conflict with Media Insight Engine

```
WorkflowExecutionLambdaDLQ already exists in stack arn:aws:cloudformation:us-east-1:xxxx:stack/mie202003-3/cd9rrrr
```

**Comment by ianwow** [comment]
Not sure how to reproduce this. Looks like something was wrong with the way CAS was deployed.

**Comment by gmarchand** [comment]
Hello.

I have deployed MIE stack in my account. And I have deployed another stack of Content Analysis in the same Account. Due to this fixed name (without random suffix) I can't deploy Content Analysis stack.

**Comment by ianwow** [comment]
I'm investigating...

**Comment by ianwow** [comment]
@gmarchand How are you deploying MIE and Content Analysis? 

1. Building cloud formation templates from script with [build-s3-dist.sh](https://github.com/aws-solutions/aws-content-analysis/blob/development/deployment/build-s3-dist.sh)?
2. Clicking the Launch Stack button in the [README](https://github.com/aws-solutions/aws-content-analysis/blob/development/README.md)?
3. Clicking the "Launch in AWS Console" button in the [solution page?](https://aws.amazon.com/solutions/implementations/aws-content-analysis/)

I'm having trouble reproducing this issue.

**Comment by gmarchand** [comment]
Arghh, it's a long time ago. I think I deployed the stack from the README

**Comment by ianwow** [comment]
I've verified that multiple CAS and MIE instances can be deployed to the same region and on the same account. The `WorkflowExecutionLambdaDeadLetterQueue` name is a logical name. It's resource id is different for every stack, so there should be no conflicts on that resource.
